config/routes.rb
Mysms::Application.routes.draw do

  resources :students do
    resources :notes, module: :students
  end
  
  resources :courses
  
  resources :institutes
  
  root to: "students#index"
end

app/models/course.rb
class Course < ActiveRecord::Base
  attr_accessible :allocation, :description, :end_date, :name, :number_of_semesters, :start_date, :institute_id

  belongs_to :institute

  validates :name, presence: true
  validates :description, presence: true
  validates :number_of_semesters, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :allocation, presence: true
end

app/models/institute.rb
class Institute < ActiveRecord::Base
  attr_accessible :name

  has_many :courses

  validates :name, presence: true, uniqueness: true
end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :title

  belongs_to :notable, polymorphic: true

  validates :notable_type, inclusion: [Student].map(&:to_s)
  validates :title, presence: true
  validates :content, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :title, :title_id, :birth_date, :email, :first_name, :gender, :last_name, :middle_name

  belongs_to :title
  has_many :notes, as: :notable

  validates :title, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :gender, presence: true

end

app/models/title.rb
class Title < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :load_course, except: [:index]

  def index
    @courses = Course.includes(:institute).order(:name).paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def edit
  end

  def update
    if @course.update_attributes(params[:course])
      redirect_to @course, notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  private

  def load_course
    @course = Course.find(params[:id])
  end
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  before_filter :load_institute, except: [:index]

  def index
    @institutes = Institute.includes(:courses).order(:name).paginate(page: params[:page], per_page: 10)
  end

  def show
  end

  def edit
  end

  def update
    if @institute.update_attributes(params[:institute])
      redirect_to @institute, notice: 'Institute was successfully updated.'
    else
      render :edit
    end
  end

  private

  def load_institute
    @institute = Institute.find(params[:id])
  end
end

app/controllers/students/notes_controller.rb
class Students::NotesController < ApplicationController
  before_filter :set_notable
  
  def new
    @note = @notable.notes.new
  end

  def create
    @note = @notable.notes.new(params[:note])
    if @note.valid?
      @note.save!
      redirect_to @notable, notice: 'Note added.'
    else
      render :new
    end
  end

  private

  def set_notable
    @notable = Student.find(params[:student_id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  decorates_assigned :student

  before_filter :load_student, except: [:index]

  def index
    @students = Student.paginate(page: params[:page], per_page: 10).decorate
  end

  def show
  end

  def edit        
  end

  def update
    if @student.update_attributes(params[:student])
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_path, notice: 'Listing was successfully destroyed.' }  
    end
  end

  private

  def load_student
    @student = Student.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/edit.html.haml
%div.form-container

  = render 'shared/error_messages', obj: @course

  = form_for @course do |f|
    .form-group
      = f.label :name, "Course Name"
      = f.text_field :name
    .form-group
      = f.label :description, "Description"
      = f.text_area :description
    .form-group
      = f.label :number_of_semesters, "Number of Semesters"
      = f.number_field :number_of_semesters
    .form-group
      = f.label :start_date, "Start Date"
      = f.date_select :start_date
    .form-group
      = f.label :end_date, "End Date"
      = f.date_select :end_date
    .form-group
      = f.label :allocation, "Allocation"
      = f.number_field :allocation
    .form-group
      = f.label :institute, "Institute"
      = f.select_tag :institute, options_from_collection_for_select(Institute.all, :id, :name)
    .form-group
      = f.submit "Update", class: 'btn btn-success'

= link_to 'Back', courses_path, class: 'btn btn-info'

app/views/courses/index.html.haml
%h2 Course Index

%table.table.table-striped
  %tr
    %th Name
    %th Description
    %th Institute
    %th Length (semesters)
    %th Start Date
    %th End Date
    %th Allocation (max. number)
    %th
    %th
    %th
  
  - @courses.each do |course|
    %tr
      %td= course.name
      %td= course.description
      %td= course.institute&.name
      %td= course.number_of_semesters
      %td= course.start_date
      %td= course.end_date
      %td= course.allocation
      %td= link_to "Show", course_path(course)
      %td= link_to "Edit", edit_course_path(course)
      %td= link_to "Delete", course, method: :delete, data: { confirm: 'Are you sure?' }

.apple_pagination
  = will_paginate @courses

app/views/courses/show.html.haml
%h3= "#{@course.name}"

%table.table.table-striped
    %tbody
        %tr
            %th Name
            %th Description
            %th Length (semesters)
            %th Start Date
            %th End Date
            %th Allocation (max. number)
            %th Institute
            %th
            %th

        %tr
            %td= @course.name
            %td= @course.description
            %td= @course.number_of_semesters
            %td= @course.start_date
            %td= @course.end_date
            %td= @course.allocation
            %td= @course.institute.name
            %td= link_to "Edit", edit_course_path(@course)
            %td= link_to "Delete", @course, method: :delete, data: { confirm: 'Are you sure?' }

= link_to "Back", courses_path, class: 'btn btn-info'

app/views/institutes/edit.html.haml
.form-container 
    = render 'shared/error_messages', obj: @institute

    = form_for @institute do |f|
        .form-group
            = f.label :name, "Name"
            = f.text_field :name
        .form-group 
            = f.submit "Update", class: 'btn btn-success'

= link_to 'Back', institutes_path, class: 'btn btn-info'

app/views/institutes/index.html.haml
%h2 Institute Index 

%table.table.table-bordered.table-hover
  %tr
    %th Name
    %th 
    %th Courses

  - @institutes.each do |institute|
    %tr
      %td= link_to "#{institute.name}", institute_path(institute)
      %td 
        %ul.list-unstyled
          %li= link_to "Edit", edit_institute_path(institute)
      %td
        %ul.list-unstyled
          - institute.courses.each do |course| 
            %li 
              = link_to "#{course.name}", course_path(course) 

.apple_pagination 
  = will_paginate @institutes

app/views/institutes/show.html.haml
%h3= "#{@institute.name}"

%table.table.table-striped
    %tbody
        %tr
            %th Name 
            %th

        %tr
            %td= @institute.name
            %td= link_to "Edit", edit_institute_path(@institute)

= link_to "Back", institutes_path, class: 'btn btn-info'

app/views/layouts/_navbar.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "/"} My Student Management System
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        %li= link_to "Students", students_path
        %li= link_to "Courses", courses_path
        %li= link_to "Institutes", institutes_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "MySMS"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
  %body
    = render 'layouts/navbar'
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield

app/views/layouts/default.html.haml
!!!
%html
  %head
    %title Mysms
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/notes/_form.html.haml
= form_for [@notable, Note.new] do |f|
  .form-group   
    = f.text_field :title, class: 'form-control', placeholder: 'Enter a title.'
    = f.text_area :content, class: 'form-control', placeholder: 'Enter note content.'
  = f.submit class: 'btn btn-primary'

app/views/notes/new.html.haml
.form-container 
  = render partial: "notes/form", locals: { notable: @student }
  = render 'shared/error_messages', obj: @note

app/views/shared/_error_messages.html.haml
- if obj.errors.any?
  .error_field
    The form contains #{pluralize(obj.errors.count, "error")}.
    %ul.error 
      - obj.errors.full_messages.each do |msg|
        %li
          #{msg}

app/views/students/edit.html.haml
.form-container

  = render 'shared/error_messages', obj: @student

  = form_for @student do |f|
    .form-group
      = f.label :title, "Title"
      = f.select_tag :title, options_from_collection_for_select(Title.all, :id, :name )
    .form-group
      = f.label :first_name, "First Name"
      = f.text_field :first_name
    .form-group
      = f.label :middle_name, "Middle Name"
      = f.text_field :middle_name
    .form-group
      = f.label :last_name, "Surname"
      = f.text_field :last_name
    .form-group
      = f.label :email, "Email"
      = f.email_field :email
    .form-group
      = f.label :birth_date, "Date of Birth"
      = f.date_select :birth_date, class: 'input-field'
    .form-group
      = f.label :gender, "Gender"
      = f.select_tag :gender, options_for_select(["Male", "Female", "Non-Binary"])
    .form-group
      = f.submit "Update", class: 'btn btn-success'

= link_to 'Back', students_path, class: 'btn btn-info'

app/views/students/index.html.haml
%h2 Student Index

%table.table.table-striped
  %tr
    %th Name
    %th Email
    %th DOB
    %th Gender
    %th
  
  - @students.each do |student|
    %tr
      %td= student.full_name
      %td= student.email
      %td= student.birth_date
      %td= student.gender
      %td
        %ul.list-unstyled.list-inline
          %li= link_to "Add Note +", new_student_note_path(student), class: 'btn btn-default btn-sm'
          %li= link_to "Show", student_path(student)
          %li= link_to "Edit", edit_student_path(student)
          %li= link_to "Delete", student, method: :delete, data: { confirm: 'Are you sure?' }

.apple_pagination
  = will_paginate @students

app/views/students/notes/_form.html.haml
= form_for [notable, Note.new] do |f|
  .form-group   
    = f.text_field :title, class: 'form-control', placeholder: 'Enter a title.'
    = f.text_area :content, class: 'form-control', placeholder: 'Enter note content.'
  = f.submit class: 'btn btn-primary'

app/views/students/notes/new.html.haml
.form-container 
  = render partial: "form", locals: { notable: @notable }
  = render 'shared/error_messages', obj: @note

app/views/students/show.html.haml
%ul.list-unstyled.list-inline
  %li 
    %h3= "#{student.full_name}"
  %li= link_to "Add Note +", new_student_note_path(student), class: 'btn btn-success btn-sm'

%table.table.table-striped
  %tbody
    %tr
      %th Title
      %th First Name
      %th Middle Name
      %th Surname
      %th Email
      %th DOB (YYYY-MM-DD)
      %th Gender
      %th

    %tr
      %td= student.title.name
      %td= student.first_name
      %td= student.middle_name
      %td= student.last_name
      %td= student.email
      %td= student.birth_date
      %td= student.gender
      %td
        %ul.list-unstyled.list-inline
          %li= link_to "Edit", edit_student_path(student)
          %li= link_to "Delete", student, method: :delete, data: { confirm: 'Are you sure?' }
      
%h3= "Notes"
%hr
- @student.notes.each do |note|
  %h4= note.title 
  %p= note.content
  %p= "(Last updated #{time_ago_in_words(note.updated_at)} ago)" 
  %hr

= link_to "Back", students_path, class: 'btn btn-info'